### ISSUE TITLE
Tag for 0.3.0 missing from repository

### ISSUE THREAD

**Issue by matthiasbeyer** [pop-os/apt-cmd#2]
The 0.3.0 tag is missing from this repository.
Please add it.

**Comment by jacobgkau** [comment]
I don't see a release commit for 0.3.0, although I see that version is listed on https://crates.io/crates/apt-cmd/versions.

It looks like the last commit before Cargo.toml was changed to say `0.4.0` was https://github.com/pop-os/apt-cmd/commit/9597e916b9b0fc262cc3ca1e84642f979f50d77a (it changed to `0.4.0` in the next commit after that with the switch to Tokio), so I guess that's the commit that would be tagged for 0.3.0?

**Comment by matthiasbeyer** [comment]
I would say as nobody reacted to this in almost 1.5 years, we can consider this repository dead.

**Comment by jacobgkau** [comment]
I'm a member of the organization and am "reacting" now, and this project is in use within the very much active https://github.com/pop-os/upgrade, so the repo is not dead. Four of your own commits were merged after you opened this issue, and another release (with a tag) was created earlier this year, so you know the fact that nobody worked on this specific issue did not mean the repo had been abandoned. I'm sorry you feel frustrated that git tags were not created for some versions in a timely manner.

@mmstick Can you add an 0.3.0 tag pointing to https://github.com/pop-os/apt-cmd/commit/9597e916b9b0fc262cc3ca1e84642f979f50d77a so we can close this issue? I don't see an 0.4.0 listed on crates.io, so I don't think that one missing is as important (I guess we never "released" an 0.4.0 version).

**Comment by jacobgkau** [comment]
Actually, looks like I did have permissions to do it myself. 0.3.0 is now tagged here: https://github.com/pop-os/apt-cmd/releases/tag/0.3.0 

@mmstick Feel free to overwrite that tag if it should have pointed to a different commit.

**Comment by matthiasbeyer** [comment]
> @mmstick Feel free to overwrite that tag if it should have pointed to a different commit.

No, don't feel free. Tags are not supposed to change.

**Comment by jacobgkau** [comment]
It's a tag for a year-and-a-half old release that's been missing this entire time. git includes the ability to change tags, and it would clearly be better to have it point to the correct commit than to have it point to the wrong one just because it did so for one day, regardless of best practices.
